/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'purple': '#3f3cbb',
      'midnight': '#121063',
      'metal': '#565584',
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'purple': '#3f3cbb',
      'midnight': '#121063',
      'metal': '#565584',
      'tahiti': '#3ab7bf',
      'silver': '#ecebff',
      'bubble-gum': '#ff77e9',
      'bermuda': '#78dcca',
      'binance' : '#7701FF',
      'grey' : '#5F5F5F',
      'light-yellow' : '#FEF6D8',
      'green' : '#008910',
      'lgreen' : '#64db39',
      'light' : '#999999',
      'unselected' : '#B9B9B9',
      'blackbg' : '#000000',
      'lighthover' : '#E0E0E0',
      'selected' : '#666666',
      'entire' : '#F4F4F5',
      'all' : '#1F1F1F',
      'hover' : '#FFCD00',
      'whitebg' : '#FFFFFF',
      'allbg':'#F4F4F5',
      'fbg':'#252525',
      'hovergreen':'#05510e',
      'tahiti': '#3ab7bf',
      'silver': '#ecebff',
      'bubble-gum': '#ff77e9',
      'bermuda': '#78dcca',
      'grey': '#5F5F5F',
      'hblue': '#004CB2',
      'blue':'#006DFF',
    },
    extend: {},
  },
  plugins: [],
}
